This is the start of python exception
